apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS order_service;
    CREATE DATABASE IF NOT EXISTS inventory_service;