apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: saiupadhyayula007/new-notification-service:latest
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: broker.default.svc.cluster.local:29092
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schema-registry.default.svc.cluster.local:8081
            - name: LOKI_URL
              value: http://loki.default.svc.cluster.local:3100/loki/api/v1/push
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo.default.svc.cluster.local:9411
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
