apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saiupadhyayula007/new-order-service:latest
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: broker.default.svc.cluster.local:29092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.default.svc.cluster.local:3306/order_service
            - name: LOKI_URL
              value: http://loki.default.svc.cluster.local:3100/loki/api/v1/push
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo.default.svc.cluster.local:9411
            - name: INVENTORY_URL
              value: http://inventory-service.default.svc.cluster.local:8082
            - name: SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schema-registry.default.svc.cluster.local:8081
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
