apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: saiupadhyayula007/new-product-service:latest
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:password@mongodb.default.svc.cluster.local:27017/product-service?authSource=admin
            - name: LOKI_URL
              value: http://loki:3100/loki/api/v1/push
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://tempo:9411
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
